"""recipes table

Revision ID: 20da53585505
Revises: bd4da586e91c
Create Date: 2024-11-26 21:17:09.782989

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20da53585505'
down_revision = 'bd4da586e91c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recipe',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('ingredients', sa.Text(), nullable=False),
    sa.Column('instructions', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('recipe', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_recipe_timestamp'), ['timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_recipe_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipe', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_recipe_user_id'))
        batch_op.drop_index(batch_op.f('ix_recipe_timestamp'))

    op.drop_table('recipe')
    # ### end Alembic commands ###
